/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class speechplugin_quadmore_QuadmoreTTS */

#ifndef _Included_speechplugin_quadmore_QuadmoreTTS
#define _Included_speechplugin_quadmore_QuadmoreTTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     speechplugin_quadmore_QuadmoreTTS
 * Method:    SpeakDarling
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_speechplugin_quadmore_QuadmoreTTS_SpeakDarling
  (JNIEnv *, jobject, jstring);

/*
 * Class:     speechplugin_quadmore_QuadmoreTTS
 * Method:    setVoiceToken
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_speechplugin_quadmore_QuadmoreTTS_setVoiceToken
  (JNIEnv *, jobject, jstring);

/*
 * Class:     speechplugin_quadmore_QuadmoreTTS
 * Method:    getVoiceToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_speechplugin_quadmore_QuadmoreTTS_getVoiceToken
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
