/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gc_systray_SystemTrayIconManager */

#ifndef _Included_com_gc_systray_SystemTrayIconManager
#define _Included_com_gc_systray_SystemTrayIconManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: dllName */
#undef com_gc_systray_SystemTrayIconManager_mouseLeftClick
#define com_gc_systray_SystemTrayIconManager_mouseLeftClick 0L
#undef com_gc_systray_SystemTrayIconManager_mouseRightClick
#define com_gc_systray_SystemTrayIconManager_mouseRightClick 1L
#undef com_gc_systray_SystemTrayIconManager_mouseDoubleClick
#define com_gc_systray_SystemTrayIconManager_mouseDoubleClick 2L
/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeDisable
  (JNIEnv *, jobject);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeEnable
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeEnable
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeFreeImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeFreeImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeLoadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeLoadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeLoadImageFromResource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeLoadImageFromResource
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeHide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeHide
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeMoveToFront
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeRemoveTitleBar
 * Signature: (Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeRemoveTitleBar
  (JNIEnv *, jclass, jstring);
 
/*
 * Class:     com_gc_systray_SystemTrayIconManager
 * Method:    nativeGetMousePos
 * Signature: (Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_com_gc_systray_SystemTrayIconManager_nativeGetMousePos
  (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif
#endif
