/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dvbplugin_ProcessHandler */

#ifndef _Included_dvbplugin_ProcessHandler
#define _Included_dvbplugin_ProcessHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dvbplugin_ProcessHandler
 * Method:    isActive
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dvbplugin_dvbviewer_ProcessHandler_isActive
  (JNIEnv *, jobject, jstring);

/* unused
 * Class:     dvbplugin_ProcessHandler
 * Method:    stopProcess
 * Signature: (Ljava/lang/String;)V
 *
JNIEXPORT void JNICALL Java_dvbplugin_dvbviewer_ProcessHandler_stopProcess
  (JNIEnv *, jobject, jstring);
 */

/*
 * Class:     dvbplugin_ProcessHandler
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;I;I)V
 */
JNIEXPORT void JNICALL Java_dvbplugin_dvbviewer_ProcessHandler_sendMessage
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
